DROP TABLE IF EXISTS blacklist CASCADE;

DROP TABLE IF EXISTS subscription_types CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;

DROP TABLE IF EXISTS complaint_types CASCADE;
DROP TABLE IF EXISTS complaints CASCADE;

DROP TABLE IF EXISTS notification_types CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;

DROP TABLE IF EXISTS static CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS profile_ratings CASCADE;


DROP TABLE IF EXISTS preferences CASCADE;
DROP TABLE IF EXISTS profile_preferences CASCADE;

DROP TABLE IF EXISTS parameters CASCADE;
DROP TABLE IF EXISTS profile_parameter CASCADE;

DROP TABLE IF EXISTS interests CASCADE;
DROP TABLE IF EXISTS profile_interests CASCADE;

DROP TABLE IF EXISTS chats CASCADE;

DROP TABLE IF EXISTS profiles CASCADE;

DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS admins CASCADE;

DROP TABLE IF EXISTS queries CASCADE;
DROP TABLE IF EXISTS user_answer CASCADE;
