name: Up Beameye Service
run-name: ${{ github.actor }} is deploying Beameye Service
on:
  push:
    branches: [ main, dev, ci ]
  pull_request:
jobs:
  test:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci' || github.ref == 'refs/heads/work'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: test
      run: |
        # make test
        echo "TESTING AHAHAHHAHAH"
  lint:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci' || github.ref == 'refs/heads/work'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - name: golangci-lint
    #   uses: golangci/golangci-lint-action@v8
    #   with:
    #     version: v2.1
    - name: linter
      run: |
        # make lint
        echo "LINTerING AHAHAHHAHAH"
  build:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/work'
    needs: [ test, lint ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ "auth_micro", "profiles_micro", "query_micro", "users_micro" ]
    steps:
    - uses: actions/checkout@v4
    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and push ${{ matrix.image }}
      run: |
        docker build -t forus809/${{ matrix.image }}:latest -f ./${{ matrix.image }}/Dockerfile .
        docker push forus809/${{ matrix.image }}:latest

  build-db-and-backend:
    needs: [ test, lint ]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/work'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build and push db backend
      run: |
        ls
        docker build -t forus809/postgre:latest -f ./repository/db/Dockerfile .
        docker push forus809/postgre:latest
        docker build -t forus809/beameye:latest -f ./Dockerfile .
        docker push forus809/beameye:latest
  deploy:
    # if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci'
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ build, build-db-and-backend ]
    steps:
    - name: deploy our beautiful app
      run: |
        ssh -i ${{ secrets.PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
        cd ./beameye
        docker-compose pull # проверить
        docker-compose up 
